"""empty message

Revision ID: 464261ce96aa
Revises: 
Create Date: 2019-04-04 16:47:35.886240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464261ce96aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('employee_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_name', sa.String(), nullable=True),
    sa.Column('employee_role', sa.String(), nullable=True),
    sa.Column('employee_salary', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('menu',
    sa.Column('snack_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snack_name', sa.String(), nullable=True),
    sa.Column('snack_price', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('snack_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu')
    op.drop_table('employees')
    # ### end Alembic commands ###
